#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('lib', __dir__)
require 'application.rb'
require 'sha1_digester'

data_path = File.expand_path('data', __dir__)
digester = Sha1Digester.new
Application.start(data_path, digester)
